version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - yum install -y jq maven
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 060795913786.dkr.ecr.us-east-2.amazonaws.com
      - REPOSITORY_URI=060795913786.dkr.ecr.us-east-2.amazonaws.com/spring_app_latest_2
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo Building the JAR file...
      - mvn clean install

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG --platform linux/amd64 .

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing imagedefinitions.json for ECS...
      - printf '[{"name":"spring-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/demo-1.0.0.jar

